unpackaged/main/default/objects/Fellow_App_Validation__mdt/Fellow_App_Validation__mdt.object-meta.xml
<CustomObject>
    <label>Fellow App Validation</label>
    <pluralLabel>Fellow App Validations</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Fellow_App_Validation__mdt/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contact</fullName>
                <default>true</default>
                <label>Contact</label>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Background</fullName>
            </value>
            <value>
                <fullName>Preference</fullName>
            </value>
            <value>
                <fullName>CoverLetter</fullName>
            </value>
            <value>
                <fullName>References</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Fellow_App_Validation__mdt/fields/Compare1__c.field-meta.xml
<CustomField>
    <fullName>Compare1__c</fullName>
    <label>Compare1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>=</fullName>
                <default>true</default>
                <label>=</label>
            </value>
            <value>
                <fullName>&gt;</fullName>
            </value>
            <value>
                <fullName>&lt;</fullName>
            </value>
            <value>
                <fullName>&lt;=</fullName>
            </value>
            <value>
                <fullName>&gt;=</fullName>
            </value>
            <value>
                <fullName>is null</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Fellow_App_Validation__mdt/fields/Compare2__c.field-meta.xml
<CustomField>
    <fullName>Compare2__c</fullName>
    <label>Compare2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>=</fullName>
                <default>true</default>
                <label>=</label>
            </value>
            <value>
                <fullName>&gt;</fullName>
            </value>
            <value>
                <fullName>&lt;</fullName>
            </value>
            <value>
                <fullName>&lt;=</fullName>
            </value>
            <value>
                <fullName>&gt;=</fullName>
            </value>
            <value>
                <fullName>is null</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Fellow_App_Validation__mdt/fields/Compare3__c.field-meta.xml
<CustomField>
    <fullName>Compare3__c</fullName>
    <label>Compare3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>=</fullName>
                <default>true</default>
                <label>=</label>
            </value>
            <value>
                <fullName>&gt;</fullName>
            </value>
            <value>
                <fullName>&lt;</fullName>
            </value>
            <value>
                <fullName>&lt;=</fullName>
            </value>
            <value>
                <fullName>&gt;=</fullName>
            </value>
            <value>
                <fullName>is null</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Fellow_App_Validation__mdt/fields/DataType1__c.field-meta.xml
<CustomField>
    <fullName>DataType1__c</fullName>
    <label>DataType1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>String</fullName>
                <default>true</default>
                <label>String</label>
            </value>
            <value>
                <fullName>Integer</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Fellow_App_Validation__mdt/fields/DataType2__c.field-meta.xml
<CustomField>
    <fullName>DataType2__c</fullName>
    <label>DataType2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>String</fullName>
                <default>true</default>
                <label>String</label>
            </value>
            <value>
                <fullName>Integer</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Fellow_App_Validation__mdt/fields/DataType3__c.field-meta.xml
<CustomField>
    <fullName>DataType3__c</fullName>
    <label>DataType3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>String</fullName>
                <default>true</default>
                <label>String</label>
            </value>
            <value>
                <fullName>Integer</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Fellow_App_Validation__mdt/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fellow_App_Validation__mdt/fields/Fellowship_Region__c.field-meta.xml
<CustomField>
    <fullName>Fellowship_Region__c</fullName>
    <label>Fellowship Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>U.S. Fellowship</fullName>
                <default>true</default>
                <label>U.S. Fellowship</label>
            </value>
            <value>
                <fullName>China Fellowship</fullName>
            </value>
            <value>
                <fullName>India Fellowship</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Fellow_App_Validation__mdt/fields/Field1__c.field-meta.xml
<CustomField>
    <fullName>Field1__c</fullName>
    <label>Field1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fellow_App_Validation__mdt/fields/Field2__c.field-meta.xml
<CustomField>
    <fullName>Field2__c</fullName>
    <label>Field2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fellow_App_Validation__mdt/fields/Field3__c.field-meta.xml
<CustomField>
    <fullName>Field3__c</fullName>
    <label>Field3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fellow_App_Validation__mdt/fields/FieldRef1__c.field-meta.xml
<CustomField>
    <fullName>FieldRef1__c</fullName>
    <label>FieldRef1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fellow_App_Validation__mdt/fields/FieldRef2__c.field-meta.xml
<CustomField>
    <fullName>FieldRef2__c</fullName>
    <label>FieldRef2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fellow_App_Validation__mdt/fields/FieldRef3__c.field-meta.xml
<CustomField>
    <fullName>FieldRef3__c</fullName>
    <label>FieldRef3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fellow_App_Validation__mdt/fields/Validate_On__c.field-meta.xml
<CustomField>
    <fullName>Validate_On__c</fullName>
    <label>Validate On</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Save</fullName>
                <default>true</default>
                <label>Save</label>
            </value>
            <value>
                <fullName>Submit</fullName>
            </value>
            <value>
                <fullName>Save + Submit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Fellow_App_Validation__mdt/fields/Value1__c.field-meta.xml
<CustomField>
    <fullName>Value1__c</fullName>
    <label>Value1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fellow_App_Validation__mdt/fields/Value2__c.field-meta.xml
<CustomField>
    <fullName>Value2__c</fullName>
    <label>Value2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fellow_App_Validation__mdt/fields/Value3__c.field-meta.xml
<CustomField>
    <fullName>Value3__c</fullName>
    <label>Value3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fellow_Application__c/Fellow_Application__c.object-meta.xml
<CustomObject>
    <description>One-to-Many relationship with Contacts (applicants)</description>
    <label>Fellow Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fellow Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fellow_Application__c/fields/Date_Expected_Graduated_1__c.field-meta.xml
<CustomField>
    <fullName>Date_Expected_Graduated_1__c</fullName>
    <label>GRAD Expected Graduation Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Fellow_Application__c/fields/Fellowship_Applying_for__c.field-meta.xml
<CustomField>
    <fullName>Fellowship_Applying_for__c</fullName>
    <label>Fellowship Applying for?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>U.S. Fellowship</fullName>
            </value>
            <value>
                <fullName>China Fellowship</fullName>
            </value>
            <value>
                <fullName>India Fellowship</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Fellow_Application__c/fields/Graduation_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Graduation_Start_Date__c</fullName>
    <label>Graduate Degree Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Fellow_Application__c/fields/Reference_Name_1__c.field-meta.xml
<CustomField>
    <fullName>Reference_Name_1__c</fullName>
    <label>Reference Name 1</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fellow_Application__c/fields/Reference_Name_3__c.field-meta.xml
<CustomField>
    <fullName>Reference_Name_3__c</fullName>
    <label>Reference Name 3</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/FellowAppValidationHelper.cls
public with sharing class FellowAppValidationHelper {

    public FellowAppValidationHelper() {

    }

    public List<String> validateOnSave(Fellow_Application__c fApp, String category) {
        Utility.logDebugMessage('category ::' + category);
        Fellow_Application__c savedFApp = getSavedFellowApp(fApp.Id);
        Utility.logDebugMessage('savedFApp ::' + savedFApp);
        Utility.logDebugMessage('region ::' + savedFApp.Fellowship_Applying_for__c);
        List<Fellow_App_Validation__mdt> validations = getSaveValidations(category, savedFApp.Fellowship_Applying_for__c);
        if (Test.isRunningTest()) validations.addAll(addAdditionalValidation());
        Utility.logDebugMessage('validations ::' + validations);
        return validateAll(validations, fApp, savedFApp);
    }

    private Fellow_Application__c getSavedFellowApp(Id fAppId) {
        try {
            String sql = Utility.queryStringForSobject('Fellow_Application__c');
            sql += ' WHERE Id = \'' + fAppId + '\'';
            return Database.query(sql);
        }
        catch (Exception e) {
            // nothing
        }
        return null;
    }

    public List<String> validateOnSubmit(Fellow_Application__c fApp) {
        Fellow_Application__c savedFApp = getSavedFellowApp(fApp.Id);
        Utility.logDebugMessage('savedFApp ::' + savedFApp);
        List<Fellow_App_Validation__mdt> validations = getSubmitValidations(savedFApp.Fellowship_Applying_for__c);
        Utility.logDebugMessage('validations ::' + validations);
        if (Test.isRunningTest()) validations.addAll(addAdditionalValidation());
        Utility.logDebugMessage('validations ::' + validations);
        return validateAll(validations, fApp, savedFApp);
    }

    public List<Fellow_App_Validation__mdt> getSubmitValidations(String region) {
        return [SELECT Id, Error_Message__c,
                    Field1__c, Compare1__c, FieldRef1__c, Value1__c, DataType1__c,
                    Field2__c, Compare2__c, FieldRef2__c, Value2__c, DataType2__c,
                    Field3__c, Compare3__c, FieldRef3__c, Value3__c, DataType3__c
                FROM Fellow_App_Validation__mdt
                WHERE Active__c = true
                    AND Validate_On__c IN ('Save', 'Save + Submit')
                    AND (Fellowship_Region__c = :region OR Fellowship_Region__c = null)];
    }

    public List<Fellow_App_Validation__mdt> getSaveValidations(String category, String region) {
        Utility.logDebugMessage([SELECT Id, Error_Message__c,
                    Field1__c, Compare1__c, FieldRef1__c, Value1__c, DataType1__c,
                    Field2__c, Compare2__c, FieldRef2__c, Value2__c, DataType2__c,
                    Field3__c, Compare3__c, FieldRef3__c, Value3__c, DataType3__c,
                    Fellowship_Region__c, Category__c
                FROM Fellow_App_Validation__mdt
                WHERE Active__c = true
                    AND Validate_On__c IN ('Save', 'Save + Submit')]);
        return [SELECT Id, Error_Message__c,
                    Field1__c, Compare1__c, FieldRef1__c, Value1__c, DataType1__c,
                    Field2__c, Compare2__c, FieldRef2__c, Value2__c, DataType2__c,
                    Field3__c, Compare3__c, FieldRef3__c, Value3__c, DataType3__c
                FROM Fellow_App_Validation__mdt
                WHERE Active__c = true
                    AND Validate_On__c IN ('Save', 'Save + Submit')
                    AND (Fellowship_Region__c = :region OR Fellowship_Region__c = null)
                    AND Category__c = :category];
    }

    public List<String> validateAll(List<Fellow_App_Validation__mdt> fAppValds, Fellow_Application__c fApp, Fellow_Application__c savedFApp) {
        List<String> retVal = new List<String>();
        for (Fellow_App_Validation__mdt validation : fAppValds) {
            String errMsg = validateEach(validation, fApp, savedFApp);
            if (errMsg != null) retVal.add(errMsg);
        }
        return retVal;
    }

    public String validateEach(Fellow_App_Validation__mdt fAppVald, Fellow_Application__c fApp, Fellow_Application__c savedFApp) {
        Boolean isAllMeetsCondition = true;
        Object fldVal1 = getFAppData(fApp, savedFApp, fAppVald.Field1__c);
        Object fldVal2 = (fAppVald.Value1__c == null  &&  fAppVald.FieldRef1__c != null) ? getFAppData(fApp, savedFApp, fAppVald.FieldRef1__c) : fAppVald.Value1__c;
        isAllMeetsCondition = performValidation(fldVal1, fldVal2, fAppVald.DataType1__c, fAppVald.Compare1__c);

        if (fAppVald.Field2__c != null) {
            fldVal1 = getFAppData(fApp, savedFApp, fAppVald.Field2__c);
            fldVal2 = (fAppVald.Value2__c == null  &&  fAppVald.FieldRef2__c != null) ? getFAppData(fApp, savedFApp, fAppVald.FieldRef2__c) : fAppVald.Value2__c;
            isAllMeetsCondition = isAllMeetsCondition && performValidation(fldVal1, fldVal2, fAppVald.DataType2__c, fAppVald.Compare2__c);

            if (fAppVald.Field3__c != null) {
                fldVal1 = getFAppData(fApp, savedFApp, fAppVald.Field3__c);
                fldVal2 = (fAppVald.Value3__c == null  &&  fAppVald.FieldRef3__c != null) ? getFAppData(fApp, savedFApp, fAppVald.FieldRef3__c) : fAppVald.Value3__c;
                isAllMeetsCondition = isAllMeetsCondition && performValidation(fldVal1, fldVal2, fAppVald.DataType3__c, fAppVald.Compare3__c);
            }
        }

        if (isAllMeetsCondition) return fAppVald.Error_Message__c;
        return null;
    }

    public Boolean performValidation(Object fldVal1, Object fldVal2, String dataType, String comparison) {
        // Object fldVal1 = getFAppData(fApp, fApp, fAppVald.Field1__c);
        // Object fldVal2 = (fAppVald.Value1__c == null  &&  fAppVald.FieldRef1__c != null) ? getFAppData(fApp, fApp, fAppVald.FieldRef1__c) : fAppVald.Value1__c;
        Utility.logDebugMessage('fldVal1 ::' + fldVal1);
        Utility.logDebugMessage('fldVal2 ::' + fldVal2);
        Utility.logDebugMessage('dataType ::' + dataType);
        Utility.logDebugMessage('comparison ::' + comparison);
        if (dataType == 'Date') fldVal2 = Date.valueOf(fldVal2 + ' 00:00:00');
        else if (dataType == 'Integer') fldVal2 = Integer.valueOf(fldVal2);
        Boolean meetsCondition = false;

        switch on comparison {
            when '=' {
                meetsCondition = (fldVal1 == fldVal2);
            }
            when 'is null' {
                meetsCondition = (fldVal1 == null);
            }
            when '>' {
                if (dataType == 'Date') meetsCondition = ((Date)fldVal1 > (Date)fldVal2);
                else meetsCondition = ((Integer)fldVal1 > (Integer)fldVal2);
            }
            when '>=' {
                if (dataType == 'Date') meetsCondition = ((Date)fldVal1 >= (Date)fldVal2);
                else meetsCondition = ((Integer)fldVal1 >= (Integer)fldVal2);
            }
            when '<' {
                // Utility.logDebugMessage('fldVal1 ::' + (Date)fldVal1);
                // Utility.logDebugMessage('fldVal2 ::' + (Date)fldVal2);
                if (dataType == 'Date') meetsCondition = ((Date)fldVal1 < (Date)fldVal2);
                else meetsCondition = ((Integer)fldVal1 < (Integer)fldVal2);
                Utility.logDebugMessage('meetsCondition ::' + meetsCondition);
            }
            when '<=' {
                if (dataType == 'Date') meetsCondition = ((Date)fldVal1 <= (Date)fldVal2);
                else meetsCondition = ((Integer)fldVal1 <= (Integer)fldVal2);
            }
            when else {
                meetsCondition = false;
            }
        }
        return meetsCondition;
    }

    public Object getFAppData(Fellow_Application__c tbSaved, Fellow_Application__c saved, String fieldName) {
        if (tbSaved.getPopulatedFieldsAsMap().containsKey(fieldName)) {
            return tbSaved.get(fieldName);
        }
        else {
            return saved.get(fieldName);
        }
    }

    private List<Fellow_App_Validation__mdt> addAdditionalValidation() {
        List<Fellow_App_Validation__mdt> retList = new List<Fellow_App_Validation__mdt>();

        Fellow_App_Validation__mdt validation = new Fellow_App_Validation__mdt();
        validation.Field1__c = 'Reference_Name_1__c';
        validation.Compare1__c = '=';
        validation.FieldRef1__c = 'Reference_Name_3__c';
        // validation.Value1__c = null;
        validation.DataType1__c = 'String';

        validation.Field2__c = 'Graduation_Start_Date__c';
        validation.Compare2__c = '>';
        // validation.FieldRef2__c = null;
        validation.Value2__c = '2012-12-31';
        validation.DataType2__c = 'Date';

        validation.Field3__c = 'Date_Expected_Graduated_1__c';
        validation.Compare3__c = '<=';
        validation.FieldRef3__c = 'Graduation_Start_Date__c';
        // validation.Value3__c = null;
        validation.DataType3__c = 'Date';

        validation.Fellowship_Region__c = 'U.S. Fellowship';
        validation.Category__c = 'CoverLetter';
        validation.Active__c = true;
        validation.Validate_On__c = 'Save + Submit';

        retList.add(validation);

        validation = new Fellow_App_Validation__mdt();
        validation.Field1__c = 'Reference_Name_1__c';
        validation.Compare1__c = 'is null';
        // validation.Value1__c = null;
        validation.DataType1__c = 'String';

        validation.Field2__c = 'Graduation_Start_Date__c';
        validation.Compare2__c = '<';
        // validation.FieldRef2__c = null;
        validation.Value2__c = '2040-12-31';
        validation.DataType2__c = 'Date';

        validation.Field3__c = 'Date_Expected_Graduated_1__c';
        validation.Compare3__c = '>=';
        validation.FieldRef3__c = 'Graduation_Start_Date__c';
        // validation.Value3__c = null;
        validation.DataType3__c = 'Date';

        validation.Fellowship_Region__c = 'U.S. Fellowship';
        validation.Category__c = 'CoverLetter';
        validation.Active__c = true;
        validation.Validate_On__c = 'Save + Submit';

        retList.add(validation);

        return retList;
    }
}